global using Snail.Abstractions;
global using Snail.Abstractions.Common.Attributes;
global using Snail.Abstractions.Dependency;
global using Snail.Abstractions.Dependency.Attributes;
global using Snail.Abstractions.Dependency.Enumerations;
global using Snail.Abstractions.Dependency.Extensions;
global using Snail.Abstractions.Setting.Extensions;
global using Snail.Common.Components;
global using Snail.Common.Extensions;
global using Snail.Utilities.Collections.Extensions;
global using Snail.Utilities.Common;
global using Snail.Utilities.Common.Extensions;
global using System.Reflection;
//  引入静态助手类方法
global using static Snail.Abstractions.ConstString;
global using static Snail.Utilities.Collections.Utils.ListHelper;
global using static Snail.Utilities.Common.Utils.ArrayHelper;
global using static Snail.Utilities.Common.Utils.DelegateHelper;
global using static Snail.Utilities.Common.Utils.ObjectHelper;
global using static Snail.Utilities.Common.Utils.StringHelper;
global using static Snail.Utilities.Common.Utils.ValueTypeHelper;
global using static System.TimeSpan;
